services:
  daily-sync:
    image: 'daily-sync:latest'
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    container_name: daily-sync
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  export-garmin-sessions:
    image: 'daily-sync:latest'
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    profiles:
      - tools
    command: yarn export_garmin_sessions
